### PR TITLE
ci: fix hardhat e2e

### LINKED ISSUE #1464: Monorepo: Hardhat E2E tests failing
I've reactivated the Hardhat E2E after a fixing PR has been submitted on the Hardhat side here https://github.com/ethereumjs/ethereumjs-monorepo/pull/1391 by @ryanio which should have solved the latest known test breaking issue.

E2E tests are nevertheless still failing, see e.g. [this CI run](https://github.com/ethereumjs/ethereumjs-monorepo/runs/3553732265).

There are a lot of errors like these:

```shell
Error: src/internal/core/jsonrpc/types/input/blockTag.ts(6,14): error TS2742: The inferred type of 'rpcNewBlockTagObjectWithNumber' cannot be named without a reference to 'ethereumjs-util/node_modules/@types/bn.js'. This is likely not portable. A type annotation is necessary.
Error: src/internal/core/jsonrpc/types/input/blockTag.ts(22,14): error TS2742: The inferred type of 'rpcNewBlockTag' cannot be named without a reference to 'ethereumjs-util/node_modules/@types/bn.js'. This is likely not portable. A type annotation is necessary.
Error: src/internal/core/jsonrpc/types/input/blockTag.ts(31,14): error TS2742: The inferred type of 'optionalRpcNewBlockTag' cannot be named without a reference to 'ethereumjs-util/node_modules/@types/bn.js'. This is likely not portable. A type annotation is necessary.
Error: src/internal/core/jsonrpc/types/input/blockTag.ts(36,14): error TS2742: The inferred type of 'rpcOldBlockTag' cannot be named without a reference to 'ethereumjs-util/node_modules/@types/bn.js'. This is likely not portable. A type annotation is necessary.
```

This should be examined and fixed.

### PR DESCRIPTION
**Pull request by ryanio**
Closes #1464

### CODE REVIEW

**Comment by ryanio** [comment]
ok cool, all fixed and I tested a failure with https://github.com/ethereumjs/ethereumjs-monorepo/commit/b5b2960aaf623935316d15ff52c557540c79153d:

```
Error: src/internal/hardhat-network/provider/node.ts(169,7): error TS2322: Type 'ForkStateManager' is not assignable to type 'StateManager'.
Error: src/internal/hardhat-network/provider/node.ts(224,7): error TS2322: Type 'HardhatStateManager' is not assignable to type 'StateManager'.
```

woop! ready for review/merge

File: packages/vm/src/state/interface.ts [hunk 1]
```diff
@@ -33,6 +33,7 @@ export interface StateManager {
   accountExists(address: Address): Promise<boolean>
   cleanupTouchedAccounts(): Promise<void>
   clearOriginalStorageCache(): void
+  someNewlyAddedBreakingMethod(): void
```
Comment (holgerd77) [inline packages/vm/src/state/interface.ts]: That's a cool test, thanks for going these extra rounds, make things very concrete and explicit! 🙂

**Review by holgerd77 — APPROVED** [review]
Very cool, always impressed by these fixes, LGTM! 😄
