### ISSUE TITLE
Benchmarks build issue

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#1996]
>@ethereumjs/vm@5.9.1 build
> ../../config/cli/ts-build.sh
[Node build] Using tsconfig.prod.json
> tsc --build ./tsconfig.prod.json
[Node build] Working... DONE
Error: tsconfig.benchmarks.json(6,5): error TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.
npm ERR! Lifecycle script `build:benchmarks` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @ethereumjs/vm@5.9.1 
npm ERR!   at location: /home/runner/work/ethereumjs-monorepo/ethereumjs-monorepo/packages/vm 
Error: Process completed with exit code 1

We're now seeing this build issue for the `vm` benchmarks CI script, most likely introduced with #1992. This should be resolved before the beta release.
